version: '3'
services:
    magento:
        image: webdevops/php-apache-dev:alpine-php7
        container_name: magento
        restart: always
        user: application
        environment:
          - WEB_ALIAS_DOMAIN=store.shubhkit.com
          - WEB_DOCUMENT_ROOT=/app/pub
          - PHP_DATE_TIMEZONE=EST
          - PHP_DISPLAY_ERRORS=1
          - PHP_MEMORY_LIMIT=2048M
          - PHP_MAX_EXECUTION_TIME=300
          - PHP_POST_MAX_SIZE=500M
          - PHP_UPLOAD_MAX_FILESIZE=1024M
        volumes:
          - ./magento:/app:cached
        ports:
          - "8010:8010"
          - "443:443"
          - "32823:22"
        links:
          - mysql
    mysql:
        image: mariadb:10
        container_name: mysql
        restart: always
        ports:
          - "3306:3306"
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=magento
        volumes:
          - db-data:/var/lib/mysql
    react:
      container_name: react
      build: .
      ports:
          - "3010:3010"
      restart: unless-stopped
      links:
          - magento

    phpmyadmin:
        container_name: phpmyadmin
        restart: always
        image: phpmyadmin/phpmyadmin:latest
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - PMA_USER=root
          - PMA_PASSWORD=root
        ports:
          - "8080:8010"
        links:
          - mysql:db
        depends_on:
          - mysql

volumes:
    db-data:
        external: false
